#!/usr/bin/env python3
"""build_app.py — assemble ``LinkedIn Autocomment.app``.

A macOS application bundle is a directory with a required shape, not a compiled
artifact. This writes that shape directly rather than going through ``py2app``,
for three reasons:

* **It stays readable.** The output is a shell script, a plist and an icon. A
  reviewer can see exactly what runs, which matters in a repo contributed
  upstream where the maintainer has to trust what the build produces.
* **It adds no build dependency.** ``py2app`` is a large tool whose failures are
  notoriously opaque, and the project's rule is to prefer the standard library.
* **It does not need to freeze the interpreter.** The venv is already beside
  the code, so the bundle locates the project's own Python instead of copying
  one. That satisfies Phase 14's "does not assume a system Python" without
  shipping a second copy of every dependency.

The bundle is a build output. It is written to ``dist/`` and never committed.

Usage:
    python tools/build_app.py [--dest DIR]
"""

import argparse
import os
import plistlib
import stat
import sys

# Plain writes throughout, deliberately. Phase 7 made every writer of *project
# state* atomic, because a truncated ledger loses data nothing can recover.
# This writes a build output into dist/: a half-written launcher is repaired by
# running the build again, and there is no state to lose.

APP_NAME = "LinkedIn Autocomment"
BUNDLE_ID = "ai.cyberrick.linkedin-autocomment"
VERSION = "0.1.0"

# The launcher. Deliberately a shell script: it is the one part of the bundle a
# user might need to read when something goes wrong, and `open` gives no stdout.
#
# `exec` matters. Without it the shell stays alive as the app's parent process,
# so quitting leaves a stray shell and macOS keeps showing the app as running.
LAUNCHER = """#!/bin/bash
# Launcher for {app_name}. Generated by tools/build_app.py — do not edit here.
set -euo pipefail

REPO="{repo}"
PYTHON="$REPO/.venv/bin/python"

if [ ! -x "$PYTHON" ]; then
    /usr/bin/osascript -e 'display alert "{app_name}" message "The project environment is missing.\\n\\nExpected: {repo}/.venv\\n\\nRun ./setup.sh in the project folder, then open this app again." as critical'
    exit 1
fi

cd "$REPO"
exec "$PYTHON" -m linkedin_automation.macapp
"""


def build_info_plist(app_name=APP_NAME, bundle_id=BUNDLE_ID, version=VERSION):
    """Return the ``Info.plist`` contents as a dict.

    ``LSUIElement`` is the key that matters. It makes this an accessory app:
    no Dock icon, no menu bar takeover, just the status item. Without it a
    background service appears in the Dock and Cmd-Tab as though it were a
    document editor, and quitting it from the Dock would stop the server behind
    the operator's back.
    """
    return {
        "CFBundleName": app_name,
        "CFBundleDisplayName": app_name,
        "CFBundleIdentifier": bundle_id,
        "CFBundleVersion": version,
        "CFBundleShortVersionString": version,
        "CFBundlePackageType": "APPL",
        "CFBundleExecutable": "launcher",
        "CFBundleIconFile": "icon.icns",
        "LSMinimumSystemVersion": "12.0",
        # Accessory app: status item only, no Dock tile.
        "LSUIElement": True,
        "NSHighResolutionCapable": True,
        # The dashboard is loopback-only, but a webview loading http://
        # needs this to be allowed at all under App Transport Security.
        "NSAppTransportSecurity": {"NSAllowsLocalNetworking": True},
    }


def build_launcher(repo_root, app_name=APP_NAME):
    """Return the launcher script text for a bundle pointing at ``repo_root``."""
    return LAUNCHER.format(repo=repo_root, app_name=app_name)


def build_bundle(dest_dir, repo_root, app_name=APP_NAME):
    """Write the .app bundle under ``dest_dir``. Returns the bundle path.

    Overwrites an existing bundle in place rather than deleting the tree first:
    a recursive delete of a path built from an argument is the operation this
    project's own rules single out, and there is nothing here that a rewrite
    leaves stale.
    """
    bundle = os.path.join(dest_dir, f"{app_name}.app")
    macos_dir = os.path.join(bundle, "Contents", "MacOS")
    resources_dir = os.path.join(bundle, "Contents", "Resources")
    os.makedirs(macos_dir, exist_ok=True)
    os.makedirs(resources_dir, exist_ok=True)

    plist_path = os.path.join(bundle, "Contents", "Info.plist")
    with open(plist_path, "wb") as handle:
        plistlib.dump(build_info_plist(app_name=app_name), handle)

    launcher_path = os.path.join(macos_dir, "launcher")
    with open(launcher_path, "w", encoding="utf-8") as handle:
        handle.write(build_launcher(repo_root, app_name))

    # Without the executable bit the bundle launches with a permission error
    # and no explanation, because `open` reports nothing to the user.
    mode = os.stat(launcher_path).st_mode
    os.chmod(launcher_path, mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    with open(os.path.join(bundle, "Contents", "PkgInfo"), "w",
              encoding="utf-8") as handle:
        handle.write("APPL????")

    return bundle


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dest", default="dist",
                        help="Directory to write the bundle into (default: dist)")
    args = parser.parse_args()

    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    dest = os.path.abspath(args.dest)
    os.makedirs(dest, exist_ok=True)

    bundle = build_bundle(dest, repo_root)

    print(f"Built: {bundle}")
    print()
    print("It is unsigned, so the first open is blocked by Gatekeeper.")
    print("Right-click the app and choose Open, then confirm. Once only.")
    print()
    print("To install it: drag it into /Applications.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
