#!/usr/bin/env python3
"""build_app.py — assemble ``LinkedIn Autocomment.app``.

A macOS application bundle is a directory with a required shape, not a compiled
artifact. This writes that shape directly rather than going through ``py2app``,
for three reasons:

* **It stays readable.** The output is a shell script, a plist and an icon. A
  reviewer can see exactly what runs, which matters in a repo contributed
  upstream where the maintainer has to trust what the build produces.
* **It adds no build dependency.** ``py2app`` is a large tool whose failures are
  notoriously opaque, and the project's rule is to prefer the standard library.
* **It does not need to freeze the interpreter.** The venv is already beside
  the code, so the bundle locates the project's own Python instead of copying
  one. That satisfies Phase 14's "does not assume a system Python" without
  shipping a second copy of every dependency.

The bundle is a build output. It is written to ``dist/`` and never committed.

The bundle records the project's location at build time, so it is built on the
machine that will run it rather than copied between machines. That is also why
sending someone the .app alone does not work: it would point at a project
folder they do not have.

Usage:
    python tools/build_app.py [--dest DIR] [--install]
"""

import argparse
import os
import plistlib
import stat
import sys

# Plain writes throughout, deliberately. Phase 7 made every writer of *project
# state* atomic, because a truncated ledger loses data nothing can recover.
# This writes a build output into dist/: a half-written launcher is repaired by
# running the build again, and there is no state to lose.

APP_NAME = "LinkedIn Autocomment"
BUNDLE_ID = "ai.cyberrick.linkedin-autocomment"
VERSION = "0.1.0"

# The launcher. Deliberately a shell script: it is the one part of the bundle a
# user might need to read when something goes wrong, and `open` gives no stdout.
#
# `exec` matters. Without it the shell stays alive as the app's parent process,
# so quitting leaves a stray shell and macOS keeps showing the app as running.
LAUNCHER = """#!/bin/bash
# Launcher for {app_name}. Generated by tools/build_app.py — do not edit here.
set -euo pipefail

REPO="{repo}"
PYTHON="$REPO/.venv/bin/python"

if [ ! -x "$PYTHON" ]; then
    /usr/bin/osascript -e 'display alert "{app_name}" message "The project environment is missing.\\n\\nExpected: {repo}/.venv\\n\\nRun ./setup.sh in the project folder, then open this app again." as critical'
    exit 1
fi

cd "$REPO"
exec "$PYTHON" -m linkedin_automation.macapp
"""


def build_info_plist(app_name=APP_NAME, bundle_id=BUNDLE_ID, version=VERSION):
    """Return the ``Info.plist`` contents as a dict.

    ``LSUIElement`` decides whether this is an accessory app (status item only)
    or an ordinary one (Dock tile and Cmd-Tab). It ships **False**.

    It was True at first, on the reasoning that a background service should not
    be quittable from the Dock behind the operator's back. Quit now stops the
    server properly, so that reasoning is spent — and it was buying nothing.
    A menu bar already holding two dozen icons makes macOS drop the overflow
    silently, and the app became unreachable: a window with no way back to it
    once closed. Discoverability beats purity here.

    ``macapp_ui`` sets the activation policy at runtime too, so the module
    works the same when run outside the bundle, and ``LINKEDIN_APP_NO_DOCK=1``
    restores the accessory behaviour for anyone who wants it.
    """
    return {
        "CFBundleName": app_name,
        "CFBundleDisplayName": app_name,
        "CFBundleIdentifier": bundle_id,
        "CFBundleVersion": version,
        "CFBundleShortVersionString": version,
        "CFBundlePackageType": "APPL",
        "CFBundleExecutable": "launcher",
        "CFBundleIconFile": "icon.icns",
        "LSMinimumSystemVersion": "12.0",
        # Dock tile by default. LSUIElement True made this an accessory app
        # with a status item and nothing else, and on a menu bar already
        # holding two dozen icons macOS dropped the overflow, so there was no
        # way to reach the app at all. macapp_ui sets the activation policy at
        # runtime and can still go accessory via LINKEDIN_APP_NO_DOCK.
        "LSUIElement": False,
        "NSHighResolutionCapable": True,
        # The dashboard is loopback-only, but a webview loading http://
        # needs this to be allowed at all under App Transport Security.
        "NSAppTransportSecurity": {"NSAllowsLocalNetworking": True},
    }


def build_launcher(repo_root, app_name=APP_NAME):
    """Return the launcher script text for a bundle pointing at ``repo_root``."""
    return LAUNCHER.format(repo=repo_root, app_name=app_name)


def build_bundle(dest_dir, repo_root, app_name=APP_NAME):
    """Write the .app bundle under ``dest_dir``. Returns the bundle path.

    Overwrites an existing bundle in place rather than deleting the tree first:
    a recursive delete of a path built from an argument is the operation this
    project's own rules single out, and there is nothing here that a rewrite
    leaves stale.
    """
    bundle = os.path.join(dest_dir, f"{app_name}.app")
    macos_dir = os.path.join(bundle, "Contents", "MacOS")
    resources_dir = os.path.join(bundle, "Contents", "Resources")
    os.makedirs(macos_dir, exist_ok=True)
    os.makedirs(resources_dir, exist_ok=True)

    plist_path = os.path.join(bundle, "Contents", "Info.plist")
    with open(plist_path, "wb") as handle:
        plistlib.dump(build_info_plist(app_name=app_name), handle)

    launcher_path = os.path.join(macos_dir, "launcher")
    with open(launcher_path, "w", encoding="utf-8") as handle:
        handle.write(build_launcher(repo_root, app_name))

    # Without the executable bit the bundle launches with a permission error
    # and no explanation, because `open` reports nothing to the user.
    mode = os.stat(launcher_path).st_mode
    os.chmod(launcher_path, mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    with open(os.path.join(bundle, "Contents", "PkgInfo"), "w",
              encoding="utf-8") as handle:
        handle.write("APPL????")

    return bundle


APPLICATIONS = "/Applications"


def install_to_applications(bundle, applications=APPLICATIONS):
    """Copy the bundle into /Applications. Returns the path, or None on failure.

    Replaces any existing copy, because the launcher inside records a project
    path and a stale bundle points at wherever the project used to be.

    Uses a temporary name then a rename, so an interrupted copy cannot leave a
    half-written application sitting in /Applications looking installed.
    """
    import shutil

    # Refuse rather than create it. /Applications always exists on macOS, so a
    # missing destination means the path is wrong, and copytree would happily
    # build the whole tree and report success having installed the app
    # somewhere nobody will look.
    if not os.path.isdir(applications):
        print(f"Not a directory: {applications}")
        return None

    name = os.path.basename(bundle)
    target = os.path.join(applications, name)
    staging = os.path.join(applications, f".{name}.incoming")

    try:
        if os.path.exists(staging):
            shutil.rmtree(staging)
        shutil.copytree(bundle, staging, symlinks=True)
        if os.path.exists(target):
            shutil.rmtree(target)
        os.rename(staging, target)
        return target
    except (OSError, shutil.Error) as e:
        logger_msg = f"Could not install into {applications}: {e}"
        print(logger_msg)
        try:
            if os.path.exists(staging):
                shutil.rmtree(staging)
        except OSError:
            pass
        return None


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dest", default="dist",
                        help="Directory to write the bundle into (default: dist)")
    parser.add_argument("--install", action="store_true",
                        help="Also copy the bundle into /Applications")
    args = parser.parse_args()

    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    dest = os.path.abspath(args.dest)
    os.makedirs(dest, exist_ok=True)

    bundle = build_bundle(dest, repo_root)
    print(f"Built: {bundle}")

    if args.install:
        installed = install_to_applications(bundle)
        if installed is None:
            print()
            print(f"Could not copy into {APPLICATIONS}. Drag it there yourself:")
            print(f"  {bundle}")
        else:
            print(f"Installed: {installed}")

    print()
    print("It is unsigned, so the first open is blocked by Gatekeeper.")
    print("Right-click the app and choose Open, then confirm. Once only.")
    if not args.install:
        print()
        print("To install it: drag it into /Applications, or re-run with --install.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
